CREATE DATABASE library;
USE library;

-- TABELA AUTHORS
CREATE TABLE authors (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL
)ENGINE=InnoDB;

-- TABELA PUBLISHERS
CREATE TABLE publishers(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL
)ENGINE=InnoDB;

-- TABELA BOOKS
CREATE TABLE books(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(190) NOT NULL,
publisher_id INT,
published_year INT NOT NULL,
FOREIGN KEY (publisher_id) REFERENCES publishers(id) ON DELETE SET NULL
)ENGINE=InnoDB;

-- TABELA DE RELACIONAMENTO 
-- BOOK + AUTHORS

CREATE TABLE book_authors (
    book_id INT NOT NULL,
    author_id INT NOT NULL,
    author_order INT DEFAULT 1,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
) ENGINE=InnoDB;

